# Generated by Django 3.1.5 on 2021-02-20 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0002_auto_20200213_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circuits',
            fields=[
                ('circuitid', models.AutoField(db_column='circuitId', primary_key=True, serialize=False)),
                ('circuitref', models.CharField(db_column='circuitRef', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('alt', models.IntegerField(blank=True, null=True)),
                ('url', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'circuits',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Constructorresults',
            fields=[
                ('constructorresultsid', models.AutoField(db_column='constructorResultsId', primary_key=True, serialize=False)),
                ('raceid', models.IntegerField(db_column='raceId')),
                ('constructorid', models.IntegerField(db_column='constructorId')),
                ('points', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'constructorResults',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Constructors',
            fields=[
                ('constructorid', models.AutoField(db_column='constructorId', primary_key=True, serialize=False)),
                ('constructorref', models.CharField(db_column='constructorRef', max_length=255)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'constructors',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Constructorstandings',
            fields=[
                ('constructorstandingsid', models.AutoField(db_column='constructorStandingsId', primary_key=True, serialize=False)),
                ('raceid', models.IntegerField(db_column='raceId')),
                ('constructorid', models.IntegerField(db_column='constructorId')),
                ('points', models.FloatField()),
                ('position', models.IntegerField(blank=True, null=True)),
                ('positiontext', models.CharField(blank=True, db_column='positionText', max_length=255, null=True)),
                ('wins', models.IntegerField()),
            ],
            options={
                'db_table': 'constructorStandings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('driverid', models.AutoField(db_column='driverId', primary_key=True, serialize=False)),
                ('driverref', models.CharField(db_column='driverRef', max_length=255)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=3, null=True)),
                ('forename', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('dob', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'drivers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Driverstandings',
            fields=[
                ('driverstandingsid', models.AutoField(db_column='driverStandingsId', primary_key=True, serialize=False)),
                ('raceid', models.IntegerField(db_column='raceId')),
                ('driverid', models.IntegerField(db_column='driverId')),
                ('points', models.FloatField()),
                ('position', models.IntegerField(blank=True, null=True)),
                ('positiontext', models.CharField(blank=True, db_column='positionText', max_length=255, null=True)),
                ('wins', models.IntegerField()),
            ],
            options={
                'db_table': 'driverStandings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Qualifying',
            fields=[
                ('qualifyid', models.AutoField(db_column='qualifyId', primary_key=True, serialize=False)),
                ('raceid', models.IntegerField(db_column='raceId')),
                ('driverid', models.IntegerField(db_column='driverId')),
                ('constructorid', models.IntegerField(db_column='constructorId')),
                ('number', models.IntegerField()),
                ('position', models.IntegerField(blank=True, null=True)),
                ('q1', models.CharField(blank=True, max_length=255, null=True)),
                ('q2', models.CharField(blank=True, max_length=255, null=True)),
                ('q3', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'qualifying',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Races',
            fields=[
                ('raceid', models.AutoField(db_column='raceId', primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('round', models.IntegerField()),
                ('circuitid', models.IntegerField(db_column='circuitId')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'races',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('resultid', models.AutoField(db_column='resultId', primary_key=True, serialize=False)),
                ('raceid', models.IntegerField(db_column='raceId')),
                ('driverid', models.IntegerField(db_column='driverId')),
                ('constructorid', models.IntegerField(db_column='constructorId')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('grid', models.IntegerField()),
                ('position', models.IntegerField(blank=True, null=True)),
                ('positiontext', models.CharField(db_column='positionText', max_length=255)),
                ('positionorder', models.IntegerField(db_column='positionOrder')),
                ('points', models.FloatField()),
                ('laps', models.IntegerField()),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
                ('milliseconds', models.IntegerField(blank=True, null=True)),
                ('fastestlap', models.IntegerField(blank=True, db_column='fastestLap', null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('fastestlaptime', models.CharField(blank=True, db_column='fastestLapTime', max_length=255, null=True)),
                ('fastestlapspeed', models.CharField(blank=True, db_column='fastestLapSpeed', max_length=255, null=True)),
                ('statusid', models.IntegerField(db_column='statusId')),
            ],
            options={
                'db_table': 'results',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'seasons',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('statusid', models.AutoField(db_column='statusId', primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'status',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pitstops',
            fields=[
                ('raceid', models.IntegerField(db_column='raceId', primary_key=True, serialize=False)),
                ('driverid', models.IntegerField(db_column='driverId')),
                ('stop', models.IntegerField()),
                ('lap', models.IntegerField()),
                ('time', models.TimeField()),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('milliseconds', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pitStops',
                'managed': True,
                'unique_together': {('raceid', 'driverid', 'stop')},
            },
        ),
        migrations.CreateModel(
            name='Laptimes',
            fields=[
                ('raceid', models.IntegerField(db_column='raceId', primary_key=True, serialize=False)),
                ('driverid', models.IntegerField(db_column='driverId')),
                ('lap', models.IntegerField()),
                ('position', models.IntegerField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
                ('milliseconds', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lapTimes',
                'managed': True,
                'unique_together': {('raceid', 'driverid', 'lap')},
            },
        ),
    ]
