# Generated by Django 3.1.5 on 2021-03-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0004_auto_20210220_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constructorresults',
            fields=[
                ('constructorresultsid', models.AutoField(db_column='constructorResultsId', primary_key=True, serialize=False)),
                ('raceid', models.IntegerField(db_column='raceId')),
                ('constructorid', models.IntegerField(db_column='constructorId')),
                ('points', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'constructorResults',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Constructors',
            fields=[
                ('constructorid', models.AutoField(db_column='constructorId', primary_key=True, serialize=False)),
                ('constructorref', models.CharField(db_column='constructorRef', max_length=255)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'constructors',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('driverid', models.AutoField(db_column='driverId', primary_key=True, serialize=False)),
                ('driverref', models.CharField(db_column='driverRef', max_length=255)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=3, null=True)),
                ('forename', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('dob', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'drivers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Driverstandings',
            fields=[
                ('driverstandingsid', models.AutoField(db_column='driverStandingsId', primary_key=True, serialize=False)),
                ('raceid', models.IntegerField(db_column='raceId')),
                ('driverid', models.IntegerField(db_column='driverId')),
                ('points', models.FloatField()),
                ('position', models.IntegerField(blank=True, null=True)),
                ('positiontext', models.CharField(blank=True, db_column='positionText', max_length=255, null=True)),
                ('wins', models.IntegerField()),
            ],
            options={
                'db_table': 'driverStandings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Julian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_to_jd', models.DateTimeField()),
                ('jd_to_date', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Races',
            fields=[
                ('raceid', models.AutoField(db_column='raceId', primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('round', models.IntegerField()),
                ('circuitid', models.IntegerField(db_column='circuitId')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'races',
                'managed': True,
            },
        ),
    ]
